# Generated by Django 5.0.1 on 2024-01-05 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='price',
        ),
        migrations.AddField(
            model_name='account',
            name='Service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='share_api.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='screen_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
