# Generated by Django 5.0.1 on 2024-01-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='period',
            field=models.CharField(choices=[('T', 'Three Months'), ('S', 'Six Months'), ('N', 'Nine Months')], default='T', max_length=1),
        ),
    ]
