# Generated by Django 5.0.1 on 2024-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='platform',
            field=models.CharField(max_length=255),
        ),
    ]
