# Generated by Django 5.0.1 on 2024-01-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0002_alter_service_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
    ]
