# Generated by Django 5.0.1 on 2024-01-07 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0002_screen_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screen',
            name='subscribed_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screen',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screens', to='share_api.customer'),
        ),
    ]
