# Generated by Django 5.0.1 on 2024-01-07 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0003_screen_password_screen_subscribed_at_screen_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='account',
        ),
        migrations.AddField(
            model_name='screen',
            name='Service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='share_api.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screen',
            name='period',
            field=models.CharField(blank=True, choices=[('T', 'Three Months'), ('S', 'Six Months'), ('N', 'Nine Months')], default='T', max_length=1, null=True),
        ),
    ]
