# Generated by Django 5.0.1 on 2024-01-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0003_remove_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='screen_price',
        ),
    ]
