# Generated by Django 5.0.1 on 2024-01-07 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0004_remove_account_customer_remove_screen_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='screen',
            old_name='Service',
            new_name='service',
        ),
        migrations.AddField(
            model_name='screen',
            name='credentials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='share_api.credentials'),
            preserve_default=False,
        ),
    ]
