# Generated by Django 5.0.1 on 2024-01-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0005_credentials_rename_service_screen_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='password',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='username',
        ),
        migrations.AddField(
            model_name='screen',
            name='bulk',
            field=models.BooleanField(default=False),
        ),
    ]
