# Generated by Django 5.0.1 on 2024-01-13 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0005_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='share_api.service'),
        ),
    ]
