# Generated by Django 5.0.1 on 2024-01-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0006_alter_feature_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
