# Generated by Django 5.0.1 on 2024-01-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0007_screen_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='subscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
