# Generated by Django 5.0.1 on 2024-01-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0008_alter_screen_subscribed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='subscribed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
