# Generated by Django 5.0.1 on 2024-02-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0010_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='comercial_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
