# Generated by Django 5.0.2 on 2024-02-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0011_service_comercial_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('S', 'Started'), ('P', 'Processing'), ('C', 'Completed')], default='S', max_length=1)),
                ('screen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='share_api.screen')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='share_api.service')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='api/images')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_receipt', to='share_api.order')),
            ],
        ),
    ]
