# Generated by Django 5.0.2 on 2024-02-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0014_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='period',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
