# Generated by Django 5.0.2 on 2024-02-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0017_account_screen_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='password',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='service',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='username',
        ),
    ]
