# Generated by Django 5.0.2 on 2024-02-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0018_remove_screen_password_remove_screen_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screen',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
