# Generated by Django 5.0.2 on 2024-02-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0019_screen_password_screen_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='share_api.service'),
            preserve_default=False,
        ),
    ]
