# Generated by Django 5.0.2 on 2024-02-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0020_screen_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='position',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
