# Generated by Django 5.0.2 on 2024-02-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0021_screen_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='period',
            field=models.CharField(blank=True, choices=[('O', 'One Month'), ('T', 'Three Months'), ('S', 'Six Months'), ('N', 'Nine Months')], default='T', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='position',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
