# Generated by Django 5.0.2 on 2024-02-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0022_alter_screen_period_alter_screen_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='days',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
