# Generated by Django 5.0.2 on 2024-03-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0028_order_customer_email_order_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='screen_id',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
